### ISSUE TITLE
Builder implementation won't establish a proper build graph.

### ISSUE THREAD

**Issue by jakemac53** [dart-league/sass_builder#1]
The sass package uses `dart:io` directly in the `render` call, and doesn't provide a way to inject a different file system as far as I know (one that would use `buildStep#readAsString` to read files).

There are a few issues going on here:

1. The `build` package doesn't know what files were actually read, so if you have `foo.sass` that imports `bar.sass`  and `bar.sass` changes, it won't re-compile your `foo.sass` file, it will only re-compile when `foo.sass` changes.
2. This will only work at all in the `build_runner` environment, or other environments where the file system has a standard layout. It will not for instance work in `bazel`.
3. Even if the sass package supported injecting a file system, I think it uses synchronous read/write apis which are not directly supported by the build package (because not all implementations can support it today).

One possible workaround which would at least function in all contexts where dart:io exists is to use the build apis to read in all transitively reachable sass files (this would require some parsing of the sass files), and then create a temp directory using dart:io where you write out all those files, and then call render with a custom package resolver that resolves to files in that directory. Then you will need to read back all the output files (using dart:io again), and re-write them using `buildStep#writeAsString`.

This is roughly what the sassc transformer  does today for instance, and while a bit cumbersome/hacky it does work in all current contexts. See [consumeTransitiveSassDeps](https://github.com/google/dart-scissors/blob/dc4274542f609d21977f1171d8fe81fce635b456/lib/src/sass/transformer.dart#L83) and [runSassC](https://github.com/google/dart-scissors/blob/dc4274542f609d21977f1171d8fe81fce635b456/lib/src/sass/sassc_runner.dart#L53) for instance. Note that this is a bit different because its actually spinning up a new process (sassc), but the same concepts should apply.

cc @nex3, not sure if you have a better idea that could get this working in an async only environment with a custom file system implementation.

**Comment by nex3** [comment]
We do plan to add support for custom importers in Dart, but you're right that asynchrony will pose a problem. This is a tension that I think will ultimately need to be addressed at the language level.

Dart Sass needs to provide a synchronous API, in part for compatibility with Node Sass's API but also because there's likely to be a noticeable performance hit if we `Future`-ify the whole implementaiton. But once we have that API, there's no way to provide an async API short of duplicating everything.

More abstractly, Dart's asynchrony story has always had an issue where it's impossible to write code that's *polymorphic over a/synchrony*. An algorithm must be written to be synchronous or asynchronous and can't be used in the other direction without re-writing it, and we're getting to the point where this is causing serious problems.

**Comment by luisvt** [comment]
maybe we should wait for https://github.com/dart-lang/build/issues/213 to be solved

**Comment by jakemac53** [comment]
Actually, this is a good example of why I never added that functionality to the build package in the first place :). You really don't want it here, as there is a clear 1:1 mapping of input sass files to output css files (as far as I know at least?).

If you use an "aggregate" builder then you lose incrementality, you always end up rebuilding all your sass files if any one of them changes instead of just the ones that actually need to be rebuilt.

**Comment by luisvt** [comment]
In general files that begins with `_` doesn't produces `css` file so there is no 1:1 mapping. We should always rebuild the main files when the sub files change.

**Comment by jakemac53** [comment]
> In general files that begins with _ doesn't produces css file so there is no 1:1 mapping.

There is still a 1:1 mapping, you just don't care about some of the sass files right? You can skip entirely the ones that start with an `_`.

The AggregateTransformer model is really designed for the many:1 case (many inputs => 1 output). Afaik this is the only valid use case for it, but it is consistently used today for things other than that which has caused pain in the past because it is consistently used for the 1:1 case (which becomes in reality a single many:many step when used this way).

> We should always rebuild the main files when the sub files change.

Yes, and you can still have that by reading those files using the `buildStep`. The difference is you only want to invalidate the css outputs that were actually affected by the sass files that were changed, not _all_ css files in the whole package. With an aggregate transformer pattern all outputs depend on all inputs, and there is only a single build action that does everything (and has to re-run in its entirety). The larger your package is the worse this gets, and it can become quite painful.

As an illustration, consider a package with 4 sass files, `a.sass`, `b.sass`, `c.sass`  and `d.sass`, where `b` and `c` import `a`, and `d` imports `b`. The dependency graph looks like this:

![imports](https://cloud.githubusercontent.com/assets/984921/23371690/cb16aa48-fccd-11e6-99fd-7c0ee85e6983.png)

With the aggregate transformer approach, your build graph looks like this because all css files are dependent on all sass files (orange == input nodes, blue == generated nodes):

![aggregate](https://cloud.githubusercontent.com/assets/984921/23371710/db2d13c2-fccd-11e6-8acf-602f62c2b286.png)

With the regular `Builder` approach it looks like this:

![ideal](https://cloud.githubusercontent.com/assets/984921/23371721/e9f5b7b0-fccd-11e6-8eda-4b3bb6353c82.png)

Whenever an orange node is updated, all blue nodes that depend on it need to be regenerated, so in the 2nd approach you generally do less work on typical edits, only an edit to `a.sass` would require a full rebuild, and only because everything actually imports that file.

**Comment by luisvt** [comment]
Sorry I don't understand you. Could you show a little code example?

**Comment by nshahan** [comment]
@luisvt I am working on a sass builder that will uses the temp directory strategy that @jakemac53 described. Would you consider a pull request that added this functionality to this package?

**Comment by luisvt** [comment]
of course I'll do!

**Comment by kevmoo** [comment]
Does #7 resolve this issue?

**Comment by jakemac53** [comment]
yep!
