### ISSUE TITLE
sass_builder doesn't seem to support .sass files

### ISSUE THREAD

**Issue by Alexander-Aue-Johr** [dart-league/sass_builder#13]
Just tried to use the sass_builder on my project were I use .sass files, but it seems that it only consumes scss files.

**Comment by Alexander-Aue-Johr** [comment]
The error coming up is :
Build error:
Transform BuilderTransformer: Instance of 'SassBuilder' on my_proj|primary threw error: "package:" URLs aren't supported on this platform.
@import "package:styles_proj/main"

 Where the file is home_component.sass and the file to import is under package styles_proj/lib/_main.sass

When I change everything to scss and scss syntax it works.

**Comment by wstrange** [comment]
I get the same error running angular_components_example, but I see that error on sccs files

**Comment by nshahan** [comment]
@AlexanderJohr You are right. I'm working on a fix. It looks like we are missing some important checks when dealing with .sass files.

As I see it, we have errors when:
* Parsing `@import` directives for .sass files.
* Attempting to find a .sass file when the extension is left out of the `@import` directive.

**Comment by nshahan** [comment]
@wstrange Were you simply trying to clone angular_components_example and build it? I am not seeing any problem with that use of this package.

**Comment by wstrange** [comment]
@nshahan exactly. I did clone of the examples followed by pub get

The problem went away when I did a pub upgrade.

**Comment by nshahan** [comment]
Blocked on https://github.com/sass/dart-sass/issues/202.

**Comment by nshahan** [comment]
@AlexanderJohr I created #14 to fix the issue. Feel free to test with it and let me know if there are any other problems.

**Comment by luisvt** [comment]
#14 is already merged and published, so this issue should be solve

**Comment by Alexander-Aue-Johr** [comment]
I wasn't able to test it in time. I did now, and #14 didn't resolve the issue yet. One little detail was still missing. I found the error and created a pull request: #25
It makes the regex for matching sass import rules a multiline regex.
There is also a new test which fails to import the sass imports if the regex isn't multiline.
