### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by nshahan** [dart-league/sass_builder#17]
@luisvt Can you publish a new version with the changes from #14 and #16?

I bumped the version number to 1.1.1 in the pubspec.yaml as part of #14 but it was never published. 

Let me know if you would like more details for the CHANGELOG or README.

**Comment by kevmoo** [comment]
Hey, @luisvt – any help here?

**Comment by luisvt** [comment]
you both were added as writers to this repo and as uplodares in pub, and the version 1.1.1 is already published
