### ISSUE TITLE
Add a changelog!

### ISSUE THREAD

**Issue by kevmoo** [dart-league/sass_builder#19]
CC @nshahan @luisvt

**Comment by 4cm4k1** [comment]
https://github.com/dart-league/sass_builder/pull/20 should fix this, I think.

**Comment by 4cm4k1** [comment]
Resolved with #20 and #21. 😄

**Comment by 4cm4k1** [comment]
By the way, I don’t think this will affect pub.dartlang.org until the next time this package is published, but it’s probably not worth a point release just to get the changelog showing. 😉

**Comment by kevmoo** [comment]
Agreed. But doing it now is great!
