### ISSUE TITLE
Keep trying to build removed scss

### ISSUE THREAD

**Issue by avstudios** [dart-league/sass_builder#2]
I have removed some scss files from the project but then getting an error:

```FileSystemException: Cannot open file, path = 'lib/admin/components/project_component.scss' (OS Error: No such file or directory, errno = 2)```

Restarting build or watch did not help.

**Comment by avstudios** [comment]
Hi Luis, did you have a chance to look at this issue? At the moment I need to keep removing sass_build_main_inputs.json to make sure the old files are not cached.

**Comment by luisvt** [comment]
I haven't

**Comment by luisvt** [comment]
I'm not able to reproduce this issue, if you have any more detailed steps to reproduce it, it would be very helpful. Also if you have a video or screenshot or a log that shows the error, it would be helpful.
