### ISSUE TITLE
Failure to find an import results in an unhelpful message

### ISSUE THREAD

**Issue by jakemac53** [dart-league/sass_builder#27]
_From @zsyphon on February 15, 2018 4:32_

Just upgraded every package I am using to the newest version and running on sdk 2.0.0-dev.26.0.

Now I am getting errors during the build that start:
[INFO] Entrypoint: Generating build script completed, took 455ms
[INFO] BuildDefinition: Building new asset graph completed, took 2.1s
[INFO] BuildDefinition: Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] sass_builder: could not read file: null
[SEVERE] sass_builder: could not read file: null
[SEVERE] sass_builder: could not read file: null
[SEVERE] sass_builder: could not read file: null

_Copied from original issue: dart-lang/angular#896_

**Comment by nshahan** [comment]
@zsyphon The linked PR has a version that should give you a better error message. 

Did you ever see any stack trace in your original build? The error thrown by the sass package should contain the name of the file that could not be read.

**Comment by zsyphon** [comment]
@nshahan Thank you! That immediately showed me what was wrong. I, of course, I had some random references left in from some learning exercises that I needed to get rid of. I never saw any errors in my original build. I was using pub build --web-compiler=dartdevc and then switched to build_runner.
