### ISSUE TITLE
Dart SDK Constraints / Package Incompatibility Question

### ISSUE THREAD

**Issue by aaronlademann-wf** [dart-league/sass_builder#32]
Hi there,

At Workiva, we are wanting to use this package as a transformer for the time-being until we transition everyone to Dart 2.

The problem we are running into is that we have packages that depend on `build ^0.5.0` because all versions at or above `^0.6.0` are not compatible with Dart SDK 1.x.

This packages says that it depends on `build_config`, and has a dev dependency on `build_runner ^0.7.0`, but the SDK constraints for the package have a lower bound of `>=1.8.0` - which seems like an oversight to me.

I also looked through the source code, and cannot find any usages of `build_config` or `build_runner` - so it is unclear to me why they are listed as dependencies / dev dependencies.

To ease the Dart 2 transition, would it make sense to release a version of this package with the `build_runner` / `build_config` dependencies removed - and then maintain a 2.x line-of-release in which those dependencies are restored, AND bump the lower bound of the Dart SDK to one of the 2.x dev releases?

@kevmoo @matanlurey @luisvt @nshahan

cc/ @robbecker-wf

**Comment by nshahan** [comment]
The dependency on build_config is used to protect against breaking changes in the format of the build.yaml file.

I'll don't recall where the build_runner dependency came from but it is listed as a dev_dependency so it shouldn't be causing problems for you when you are version solving. 

Is this an issue that you can't work around by using an older version of sass_builder or setting a dependency_override in your package? What version of the package are you depending on?

In the near future we will probably want to release v2.0.0 where we remove the transformer and barback dependency from this package.

**Comment by aaronlademann-wf** [comment]
> "Is this an issue that you can't work around by using an older version of sass_builder or setting a dependency_override in your package? What version of the package are you depending on?"

@nshahan I could downgrade us to version `1.0.1`, but then our apps would be serving un-minified CSS files (we are anxiously waiting for https://github.com/dart-league/sass_builder/issues/23). A dependency override is not an option since you can't publish packages that have overrides.

> "I'll don't recall where the build_runner dependency came from but it is listed as a dev_dependency so it shouldn't be causing problems for you when you are version solving"

Unfortunately this is not the case.  In a package that has a dev dependency of `build: ^0.5.0` and `sass_builder: ^1.1.5`, the version solver says:

_Because sass_builder >=1.1.2 depends on build >=0.11.1 <0.13.0 and build_runner 0.5.0 depends on build ^0.10.1, sass_builder >=1.1.2 is
  incompatible with build_runner 0.5.0.
And because no versions of build_runner match >0.5.0 <0.6.0, sass_builder >=1.1.2 is incompatible with build_runner ^0.5.0.
So, because w_table depends on both build_runner ^0.5.0 and sass_builder ^1.1.5, version solving failed._

> "In the near future we will probably want to release v2.0.0 where we remove the transformer and barback dependency from this package."

I guess this is the part that is confusing for me.  The dependencies are already such that the lower bound of the SDK constraint _should_ be 2.x IMO. Especially considering that if you have consumers that are wanting to use the build package instead of a transformer - they can't do that on Dart 1.x because of the `build_runner ^0.7.0` dev dependency.  Consumers like Workiva that are looking for a solution that works with Dart 1.x right now are stuck unless a version can be released without those Dart 2.x "build" pieces.

cc/ @kevmoo @robbecker-wf

**Comment by nshahan** [comment]
> Unfortunately this is not the case. In a package that has a dev dependency of build: ^0.5.0 and sass_builder: ^1.1.5, the version solver says:

Did you mean `build_runner: ^0.5.0` here? I don't think this package was ever published with dependencies compatible with `build: 0.5.0`.

**Comment by nshahan** [comment]
I do think we should plan for a release that represents the final version with a transformer. If possible it would be nice for this release to not be a breaking change so that we could just release it as a continuation of the 1.x.x line. 

We could land the outputStyle changes and perhaps publish with the build_runner dev_dependency removed. Would dependencies that look like this work for your package?

```
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  barback: ^0.15.2
  build: '>=0.11.1 <0.13.0'
  build_barback: '>=0.4.0+2 <0.6.0'
  build_config: ^0.2.1
  logging: ^0.11.3
  package_resolver: ^1.0.2
  path: ^1.4.1
  sass: ^1.1.1
  scratch_space: ^0.0.1
dev_dependencies:
  build_test: '>=0.9.1 <0.11.0'
  test: ^0.12.0
```

cc/ @kevmoo @robbecker-wf

**Comment by aaronlademann-wf** [comment]
@nshahan yes I think that would work.

**Comment by nshahan** [comment]
v1.2.0 has been published.
