### ISSUE TITLE
Mission dart:io import

### ISSUE THREAD

**Issue by daniel-v** [dart-league/sass_builder#4]
Analyzer errors out on:

`error: Undefined name 'Directory'. (undefined_identifier at [sass_builder] lib\sass_builder.dart:18)`

Fix should be trivial, I'll do a PR.

**Comment by avstudios** [comment]
Just noticed the same thing in 0.1.0 version. Thanks Daniel for fixing it.

**Comment by avstudios** [comment]
Sorry, I was wrong. Still the same issue. To make it work again I had to revert lib to the previous version.
