### ISSUE TITLE
"pub run build_runner serve" doesn't transpile scss file to css

### ISSUE THREAD

**Issue by hamedsbt** [dart-league/sass_builder#57]
**pubspec.yaml file:**
````name: AWebApp
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  mdc_web:
  
dev_dependencies:
  build_config: '>=0.2.6 <0.5.0'
  angular_test: ^2.3.0
  sass_builder: ^2.1.3
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0
````

**build.yaml file:**
````targets:
  $default:
    builders:
      angular_components|scss_builder:
        enabled: True
        options:
          outputStyle: compressed
````

**my_component.scss file:**
```@import 'package:angular_components/css/material/material';
@import 'package:angular_components/material_button/mixins';
@include button-background-color('#myButton', green);
@include button-color('#myButton', yellow);
.mdc-layout-grid__cell {
    border: 1px solid #000000;
}
.my-card {
    height: 200px;
    width: 150px;
}
```

Why command `pub run build_runner serve` doesn't create the .css and .map files?!

**Comment by nshahan** [comment]
Are you getting an error message? 
What is meant to consume the .css files? 

By default the .css files are built to a temporary hidden directory that build_runner provides access to for the next stage of the build. You should be able to find them from the root directory of your package at `.dart_tool/build/generated/<your_package>`.

If you need them generated to the source directory, look at the build_config option `build_to`.
https://github.com/dart-lang/build/blob/master/build_config/README.md#defining-builders-to-apply-to-dependents-similar-to-transformers

**Comment by hamedsbt** [comment]
Thank you for your fast reply. It seems my problem was misunderstood.
