### ISSUE TITLE
pub get unable to resolve dependencies

### ISSUE THREAD

**Issue by mgoergner** [dart-league/sass_builder#58]
I get this error when I run pub get:

`Resolving dependencies... 
Because sass depends on sass_builder ^2.1.2 which depends on sass ^1.11.0, sass ^1.11.0 is required.
So, because sass is 0.0.0, version solving failed.`

New stagehand web-simple project & followed all instructions. Also installed Sass manually with brew, however this should not be needed manually as far as I can tell.

**Comment by nshahan** [comment]
This is a confusing message. Can you post the contents of your `pubspec.yaml` file? My only guess is that you have a name conflict between the name of your package and the sass package so version solving is getting confused.

> New stagehand web-simple project & followed all instructions.

The stagehand web-simple project does not have a dependency on sass_builder. What instructions did you follow?

**Comment by mgoergner** [comment]
This solved it. Called the project folder "sass". Thanks a lot for the swift help!
