### ISSUE TITLE
Unsupported uri scheme `http`.

### ISSUE THREAD

**Issue by avstudios** [dart-league/sass_builder#6]
I've updated sass_builder to 0.1.1 and ng_bootstrap to 0.6.4+1 versions. And when running watcher I see an error: 
```Invalid argument(s): Uri http://localhost:58689/packages/bootstrap_sass/scss/mixins must have scheme 'file:'.```

**Comment by luisvt** [comment]
could you show me the code you are using in the `scss` file. It looks like you are trying to import a file from the server, which is not possible, and I don't think it will be in the future.

`sass_builder` only can read from local files either located in the same project directory or in a dart package. For example:

```scss
// importing local file relative to this file
@import "path/to/my/file";

// importing file located inside a package
@import "package:path/to/file/in/package"
```

so if you want to import `mixins` file from `bootstrap_sass` you should use:

```scss
@import "package:bootstrap_sass/scss/mixins";
```

**Comment by luisvt** [comment]
Since no more comments from @avstudios I will close this issue
