### ISSUE TITLE
Imports from current project/package not working.

### ISSUE THREAD

**Issue by lelabo-m** [dart-league/sass_builder#60]
Hi,

I am trying to load a front-end framework from the `style.scss` called by the index.html.

I am trying to load resources using this path syntax but it's not working while using the relative path (with `'../lib/my/resources/path'`) works.
```scss
@import url(https://fonts.googleapis.com/css?family=Roboto);
@import url(https://fonts.googleapis.com/css?family=Material+Icons);


@import 'package:survey_landing/lib/assets/materialize/sass/components/color-variables';
$primary-color: color("grey", "darken-4") !default;
@import 'package:survey_landing/lib/assets/materialize/sass/materialize';
```

I am not sure if it is not working because it is not a dependency but the current application or because this syntax is not supported.
It would be nice if the package syntax was supported at it is clearer for users discovering dart/angular dart.

**Comment by simolus3** [comment]
I think the problem is that you're manually including the `lib/` in your import uri. In Dart, `package:` imports already refer to files in `lib/` so that's not necessary. If you had a file `lib/foo.scss` in a package, you'd import it with `package:your_package/foo`.
