### ISSUE TITLE
Support for Null safety

### ISSUE THREAD

**Issue by matehat** [dart-league/sass_builder#63]
Hello,

We have a AngularDart project that uses sass_builder to generate styles for our components, and the community (build, angular, analyzer and even sass) is converging towards full null safety support, but we can see that sass_builder will be the choking point for us in the near future.

Do you plan to support null safety soon?

**Comment by matehat** [comment]
I see that support is already suggested in #62. Once that PR merges, this issue can be closed.

**Comment by simolus3** [comment]
As you mentioned we do support null safety now :)
