### ISSUE TITLE
Update GitHub page to point website at https://pub.dartlang.org/packages/sass_builder

### ISSUE THREAD

**Issue by kevmoo** [dart-league/sass_builder#9]
Tis convention

**Comment by luisvt** [comment]
what GitHub page are you talking about?

**Comment by kevmoo** [comment]
The page URL that shows when you open the GitHub repo

From mobile. Sorry for brevity and/or spelling.

**Comment by luisvt** [comment]
I still don't understand what page you refer to.

**Comment by kevmoo** [comment]
![screen shot 2017-11-16 at 12 52 11 pm](https://user-images.githubusercontent.com/17034/32915243-11ae19f0-cacd-11e7-93cd-caad17aebd54.png)

**Comment by luisvt** [comment]
ahh got it

**Comment by luisvt** [comment]
done

**Comment by kevmoo** [comment]
Thanks!
